thenewboston/music/urls.py
from django.conf.urls import url
from . import views
#from thenewboston.thenewboston.music import views

app_name = 'music'

urlpatterns = [
    # /music/
    url(r'^$', views.index, name='index'),
    # /music/id
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name="detail"),
]

thenewboston/thenewboston/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

thenewboston/music/models.py
from __future__ import unicode_literals

from django.db import models


class Album(models.Model):
    """
    Description: Album Description
    """
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=350)
    genre = models.CharField(max_length=150)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + " - " + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)

    def __str__(self):
        return self.song_title

thenewboston/music/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from .models import Album
# Create your views here.

def index(request):
    all_albums = Album.objects.all()
    context_data = {
        'all_albums': all_albums,
    }
    return render(request, 'music/index.html', context_data)

def detail(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    return render(request, "music/detail.html", {'album': album})

# Vid nr 22

thenewboston/music/templates/music/detail.html
<img src="{{ album.album_logo }}">

<h1> Album Title </h1>
<h2> Artist </h2>

<ul>
    {% for song in album.song_set.all %}
        <li>{{ song.song_title }} - {{ song.file_type }}</li>
    {%endfor%}
</ul>

thenewboston/music/templates/music/index.html
{% if all_albums %}
<ul>
    {% for album in all_albums %}
    <li><a href="{% url 'music:detail' album.id %}">{{album.album_title}}</li>
    {%endfor%}
</ul>
{%else%}
    <h3>No albums</h3>
{%endif%}